### ISSUE TITLE
Use consul group for directory

### ISSUE THREAD

**Issue by arthurk** [status-im/infra-role-consul-service#1]
Current consul dir is owned by `adm` which can be replaced with the `consul` group. It seems this has been done manually on the servers already. The diff shows:

```diff
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "group": 500,
+    "group": 4,
     "path": "/etc/consul"
 }
```
So running the current role would replace it with `adm` again

**Comment by jakubgs** [comment]
Misclick?

**Comment by jakubgs** [comment]
Hm, the group is correct, but we don't set an owner:
https://github.com/status-im/infra-role-bootstrap/blob/30f2ec7d27804d50e45ea3e9362eed1f1704335d/tasks/consul/config.yml#L18-L24

**Comment by jakubgs** [comment]
Ah, but it gets overwrittedn by this role:
https://github.com/status-im/infra-role-consul-service/blob/b1d5ad5caa7d7a036fd175292fa497175bb7c54c/tasks/main.yml#L2-L10

**Comment by jakubgs** [comment]
But they are readable to everyone else, so it works fine.

**Comment by jakubgs** [comment]
Already the case:
https://github.com/status-im/infra-role-consul-service/blob/4d7c9c606f5e039a22c34ba93961d05056c0e002/tasks/linux.yml#L5
And in bootstrap.
https://github.com/status-im/infra-role-bootstrap-linux/blob/b8653d82f400e7e921733ad6d6089d7c8e84a253/defaults/main.yml#L181
